spring:
  application:
    name: api-financas
  datasource:
    url: jdbc:mysql://localhost:3307/db_financas?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: user_financas
    password: IFMGadmin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  main:
    banner-mode: console